spring.datasource.url=jdbc:postgresql://localhost/liter_alura
spring.datasource.username=postgres
spring.datasource.password=23278
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.show-sql=false
spring.jpa.format-sql=true
spring.jpa.hibernate.ddl-auto=update
log4j.logger.org.hibernate.SQL=OFF
log4j.logger.org.hibernate.type.descriptor.sql.BasicBinder=OFF
log4j.logger.org.hibernate=ERROR